name: HologramChat
version: '${project.version}'
main: me.niko302.hologramchat.HologramChat
api-version: '1.20'
depend: [ProtocolLib]
softdepend: [PlaceholderAPI, Essentials]

commands:
  hologramchatreload:
    description: Reloads the configuration for HologramChat.
    usage: /<command>
    permission: hologramchat.reload